### ISSUE TITLE
LD_LIBRARY_PATH should be set as variable

### ISSUE THREAD

**Issue by anastacia-maletskaya-epam** [lean-delivery/ansible-role-oracle-instant-client#4]
##### SUMMARY

Make "/usr/lib/oracle/12.1/client64/lib" (LD_LIBRARY_PATH) path as variable in defaults/main.yml

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.5.8
```

##### EXPECTED RESULTS

Path "/usr/lib/oracle/12.1/client64/lib" should be set as variable in defaults/main.yml

##### ACTUAL RESULTS

```
- name: "Add Oracle client to library path"
  lineinfile:
    dest: "/etc/ld.so.conf.d/oracle.conf"
    line: "/usr/lib/oracle/12.1/client64/lib"
    insertbefore: "BOF"
    create: True
  notify: "Run ldconfig"
  become: True
```
